name: JMeter Test and Publish Report

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    name: performance test - ${{ github.event.inputs.choice }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install JMeter
        run: |
          wget -q https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.2.tgz
          tar -xzf apache-jmeter-5.6.2.tgz
          rm apache-jmeter-5.6.2.tgz
        working-directory: ${{ github.workspace }}

      - name: Run JMeter Test
        run: |
          JMETER_SCRIPT="${{ github.workspace }}/test_plan.jmx"
          JMETER_RESULTS="${{ github.workspace }}/test/JMeter/results"
          ./apache-jmeter-5.6.2/bin/jmeter -n -t "$JMETER_SCRIPT" -l "$JMETER_RESULTS/test_results.jtl"

      - name: Generate JMeter Report
        run: |
          JMETER_RESULTS="${{ github.workspace }}/test/JMeter/results"
          mkdir -p "$JMETER_RESULTS/report"
          ./apache-jmeter-5.6.2/bin/jmeter -g "$JMETER_RESULTS/test_results.jtl" -o "$JMETER_RESULTS/report"

      - name: Install Allure Framework
        run: |
          # Replace '2.14.0' with the latest version of Allure
          curl -o allure-2.14.0.zip -Ls https://github.com/allure-framework/allure2/releases/download/2.14.0/allure-2.14.0.zip
          unzip allure-2.14.0.zip -d ${{ github.workspace }}
          rm allure-2.14.0.zip
          chmod +x ${{ github.workspace }}/allure-2.14.0/bin/allure

      - name: Generate Allure Report
        run: |
          JMETER_RESULTS="${{ github.workspace }}/test/JMeter/results"
          ${{ github.workspace }}/allure-2.14.0/bin/allure generate "$JMETER_RESULTS/report" -o "$JMETER_RESULTS/allure-report"

          # Merge the Allure results
          allurectl plugins install -f -v 2.14.0
          allurectl plugins merge "$JMETER_RESULTS/allure-report" --clean

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: allure-report-${{ github.run_number }}
          path: ${{ github.workspace }}/test/JMeter/results/allure-report/

      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: allure-report-${{ github.run_number }}
