name: Example Test with JMeter and Generate Report
run-name: Performance tests ran by @${{ github.actor }} - run number ${{ github.run_number }}
on:
    workflow_dispatch:
    
    push:
     branches:
      - main

jobs:
  performance_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run JMeter Test
        run: |
          docker run --rm \
            -v $PWD:/mnt/jmeter \
            justb4/jmeter \
            -n -t /mnt/jmeter/test_plan.jmx -l /mnt/jmeter/test_results.jtl

      - name: Generate JMeter Report
        run: |
          docker run --rm \
            -v $PWD:/mnt/jmeter \
            justb4/jmeter \
            -g /mnt/jmeter/test_results.jtl -o /mnt/jmeter/report

      - name: Deploy Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report

      - name: Get Report URL
        id: report_url
        run: |
          echo "::set-output name=report_url::https://${{ github.repository_owner }}.github.io/${{ github.repository }}/report"

      - name: Print Report URL
        run: |
          echo "Report URL: ${{ steps.report_url.outputs.report_url }}"
