name: Example Test with JMeter (using container)

on:
  push:
    branches:
      - main

jobs:
  performance_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run JMeter Test
        run: |
          docker run --rm \
            -v $PWD:/mnt/jmeter \
            justb4/jmeter \
            -n -t /mnt/jmeter/test_plan.jmx -l /mnt/jmeter/test_results.jtl

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: example-test-results
          path: test_results.jtl
