name: JMeter Test 
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  performance_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install JMeter
        run: |
          wget -q https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.2.tgz
          tar -xzf apache-jmeter-5.6.2.tgz
          rm apache-jmeter-5.6.2.tgz
        working-directory: ${{ github.workspace }}

      - name: Run JMeter Test
        run: |
          JMETER_SCRIPT="${{ github.workspace }}/test_plan.jmx"
          JMETER_RESULTS="${{ github.workspace }}/test/JMeter/results"
          ./apache-jmeter-5.6.2/bin/jmeter -n -t "$JMETER_SCRIPT" -l "$JMETER_RESULTS/test_results.jtl"

      - name: Generate JMeter Report
        run: |
          JMETER_RESULTS="${{ github.workspace }}/test/JMeter/results"
          mkdir -p "$JMETER_RESULTS/report"
          ./apache-jmeter-5.6.2/bin/jmeter -g "$JMETER_RESULTS/test_results.jtl" -o "$JMETER_RESULTS/report"

      - name: Upload Test Report
        if: always() # This step will always run, regardless of previous steps' success
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-report
          path: ${{ github.workspace }}/test/JMeter/results/report
